import type { Patient } from "@pr_hospitalagent/types";

export type PatientSeedSpec = Omit<Patient, "passwordHash"> & { password: string };

const now = new Date();

export const patientSeedSpecs: PatientSeedSpec[] = [
  {
    id: "BN001",
    username: "bn001",
    password: "matkhaubn001",
    name: "Nguyễn Văn A",
    age: 58,
    gender: "Nam",
    ward: "Nội Tim mạch",
    diagnoses: [
      "Tăng huyết áp",
      "Đái tháo đường type 2",
      "Nghi suy tim mất bù",
    ],
    vitals: {
      spO2: 91,
      heartRate: 102,
      bloodPressure: "148/92",
      temperature: 37.1,
      recordedAt: now,
    },
    medications: ["Amlodipine 5mg", "Metformin 500mg", "Aspirin 81mg"],
    labResults: [
      {
        name: "NT-proBNP",
        value: 2840,
        unit: "pg/mL",
        referenceRange: "<125",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "Creatinine",
        value: 1.4,
        unit: "mg/dL",
        referenceRange: "0.7-1.2",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "Hb",
        value: 11.2,
        unit: "g/dL",
        referenceRange: "13-17",
        isAbnormal: false,
        recordedAt: now,
      },
      {
        name: "HbA1c",
        value: 7.8,
        unit: "%",
        referenceRange: "<6.5",
        isAbnormal: false,
        recordedAt: now,
      },
    ],
  },
  {
    id: "BN002",
    username: "bn002",
    password: "matkhaubn002",
    name: "Trần Thị B",
    age: 45,
    gender: "Nữ",
    ward: "Nội Tổng quát",
    diagnoses: ["Đau ngực điển hình", "Tăng huyết áp"],
    vitals: {
      spO2: 97,
      heartRate: 88,
      bloodPressure: "160/100",
      temperature: 36.8,
      recordedAt: now,
    },
    medications: ["Nitroglycerin PRN", "Amlodipine 10mg"],
    labResults: [
      {
        name: "Troponin I",
        value: 0.08,
        unit: "ng/mL",
        referenceRange: "<0.04",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "CK-MB",
        value: 18,
        unit: "U/L",
        referenceRange: "<16",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "Cholesterol",
        value: 6.2,
        unit: "mmol/L",
        referenceRange: "<5.2",
        isAbnormal: true,
        recordedAt: now,
      },
    ],
  },
  {
    id: "BN003",
    username: "bn003",
    password: "matkhaubn003",
    name: "Lê Minh C",
    age: 32,
    gender: "Nam",
    ward: "Cấp cứu",
    diagnoses: ["Chấn thương đầu kín", "GCS 14"],
    vitals: {
      spO2: 98,
      heartRate: 78,
      bloodPressure: "130/80",
      temperature: 36.9,
      recordedAt: now,
    },
    medications: ["Mannitol 20%", "Paracetamol 1g IV"],
    labResults: [
      {
        name: "CT sọ não",
        value: "Không xuất huyết",
        unit: "",
        referenceRange: "Bình thường",
        isAbnormal: false,
        recordedAt: now,
      },
      {
        name: "CBC",
        value: "Bình thường",
        unit: "",
        referenceRange: "Bình thường",
        isAbnormal: false,
        recordedAt: now,
      },
      {
        name: "Glucose",
        value: 5.8,
        unit: "mmol/L",
        referenceRange: "3.9-6.1",
        isAbnormal: false,
        recordedAt: now,
      },
    ],
  },
  {
    id: "BN004",
    username: "bn004",
    password: "matkhaubn004",
    name: "Phạm Thị D",
    age: 67,
    gender: "Nữ",
    ward: "Hô hấp",
    diagnoses: ["COPD đợt cấp", "Suy hô hấp type 2"],
    vitals: {
      spO2: 86,
      heartRate: 112,
      bloodPressure: "138/84",
      temperature: 37.6,
      recordedAt: now,
    },
    medications: [
      "Salbutamol khí dung",
      "Ipratropium khí dung",
      "Methylprednisolone 40mg IV",
    ],
    labResults: [
      {
        name: "pH máu",
        value: 7.31,
        unit: "",
        referenceRange: "7.35-7.45",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "PaCO2",
        value: 58,
        unit: "mmHg",
        referenceRange: "35-45",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "PaO2",
        value: 54,
        unit: "mmHg",
        referenceRange: "80-100",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "Bạch cầu",
        value: 13.8,
        unit: "K/uL",
        referenceRange: "4-10",
        isAbnormal: true,
        recordedAt: now,
      },
    ],
  },
  {
    id: "BN005",
    username: "bn005",
    password: "matkhaubn005",
    name: "Hoàng Văn E",
    age: 71,
    gender: "Nam",
    ward: "Nội Thận",
    diagnoses: [
      "Bệnh thận mạn giai đoạn 4",
      "Tăng huyết áp",
      "Thiếu máu mạn",
    ],
    vitals: {
      spO2: 96,
      heartRate: 84,
      bloodPressure: "152/88",
      temperature: 36.7,
      recordedAt: now,
    },
    medications: [
      "Losartan 50mg",
      "Furosemide 40mg",
      "Erythropoietin tiêm dưới da",
      "Calcium carbonate 500mg",
    ],
    labResults: [
      {
        name: "Creatinine",
        value: 3.6,
        unit: "mg/dL",
        referenceRange: "0.7-1.2",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "eGFR",
        value: 22,
        unit: "mL/phút/1.73m²",
        referenceRange: ">90",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "Kali",
        value: 5.6,
        unit: "mmol/L",
        referenceRange: "3.5-5.0",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "Hb",
        value: 9.4,
        unit: "g/dL",
        referenceRange: "13-17",
        isAbnormal: true,
        recordedAt: now,
      },
    ],
  },
  {
    id: "BN006",
    username: "bn006",
    password: "matkhaubn006",
    name: "Vũ Thị F",
    age: 29,
    gender: "Nữ",
    ward: "Sản",
    diagnoses: ["Tiền sản giật nặng", "Thai 34 tuần"],
    vitals: {
      spO2: 98,
      heartRate: 96,
      bloodPressure: "168/108",
      temperature: 36.9,
      recordedAt: now,
    },
    medications: [
      "Magnesium sulfate IV",
      "Methyldopa 250mg",
      "Betamethasone 12mg IM",
    ],
    labResults: [
      {
        name: "Protein niệu 24h",
        value: 4.2,
        unit: "g/24h",
        referenceRange: "<0.3",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "Tiểu cầu",
        value: 92,
        unit: "K/uL",
        referenceRange: "150-400",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "AST",
        value: 78,
        unit: "U/L",
        referenceRange: "<40",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "Acid uric",
        value: 7.8,
        unit: "mg/dL",
        referenceRange: "2.4-6.0",
        isAbnormal: true,
        recordedAt: now,
      },
    ],
  },
  {
    id: "BN007",
    username: "bn007",
    password: "matkhaubn007",
    name: "Đặng Minh G",
    age: 8,
    gender: "Nam",
    ward: "Nhi",
    diagnoses: ["Sốt xuất huyết Dengue ngày 5", "Cảnh báo dấu hiệu nặng"],
    vitals: {
      spO2: 97,
      heartRate: 124,
      bloodPressure: "92/58",
      temperature: 38.4,
      recordedAt: now,
    },
    medications: ["Paracetamol 250mg", "Ringer lactate truyền tĩnh mạch"],
    labResults: [
      {
        name: "Tiểu cầu",
        value: 38,
        unit: "K/uL",
        referenceRange: "150-400",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "Hematocrit",
        value: 48,
        unit: "%",
        referenceRange: "35-45",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "NS1 Dengue",
        value: "Dương tính",
        unit: "",
        referenceRange: "Âm tính",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "AST",
        value: 132,
        unit: "U/L",
        referenceRange: "<40",
        isAbnormal: true,
        recordedAt: now,
      },
    ],
  },
  {
    id: "BN008",
    username: "bn008",
    password: "matkhaubn008",
    name: "Bùi Văn H",
    age: 64,
    gender: "Nam",
    ward: "Thần kinh",
    diagnoses: [
      "Đột quỵ nhồi máu não cấp",
      "Rung nhĩ",
      "Tăng huyết áp",
    ],
    vitals: {
      spO2: 95,
      heartRate: 108,
      bloodPressure: "172/96",
      temperature: 36.8,
      recordedAt: now,
    },
    medications: [
      "Alteplase tiêu sợi huyết",
      "Aspirin 81mg",
      "Atorvastatin 40mg",
    ],
    labResults: [
      {
        name: "MRI sọ não",
        value: "Nhồi máu vùng MCA trái",
        unit: "",
        referenceRange: "Bình thường",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "INR",
        value: 1.1,
        unit: "",
        referenceRange: "0.8-1.2",
        isAbnormal: false,
        recordedAt: now,
      },
      {
        name: "Glucose",
        value: 8.4,
        unit: "mmol/L",
        referenceRange: "3.9-6.1",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "LDL-C",
        value: 4.6,
        unit: "mmol/L",
        referenceRange: "<3.4",
        isAbnormal: true,
        recordedAt: now,
      },
    ],
  },
  {
    id: "BN009",
    username: "bn009",
    password: "matkhaubn009",
    name: "Ngô Thị I",
    age: 52,
    gender: "Nữ",
    ward: "Tiêu hóa",
    diagnoses: ["Viêm tụy cấp do sỏi mật", "Mất nước độ 2"],
    vitals: {
      spO2: 96,
      heartRate: 116,
      bloodPressure: "104/68",
      temperature: 38.1,
      recordedAt: now,
    },
    medications: [
      "Ringer lactate truyền tĩnh mạch",
      "Pethidine 50mg IM",
      "Pantoprazole 40mg IV",
      "Cefoperazone-sulbactam 2g IV",
    ],
    labResults: [
      {
        name: "Amylase",
        value: 824,
        unit: "U/L",
        referenceRange: "30-110",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "Lipase",
        value: 1450,
        unit: "U/L",
        referenceRange: "<60",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "Bạch cầu",
        value: 16.4,
        unit: "K/uL",
        referenceRange: "4-10",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "CRP",
        value: 142,
        unit: "mg/L",
        referenceRange: "<5",
        isAbnormal: true,
        recordedAt: now,
      },
    ],
  },
  {
    id: "BN010",
    username: "bn010",
    password: "matkhaubn010",
    name: "Đỗ Văn K",
    age: 74,
    gender: "Nam",
    ward: "Truyền nhiễm",
    diagnoses: [
      "Viêm phổi cộng đồng nặng",
      "Nhiễm khuẩn huyết",
      "Đái tháo đường type 2",
    ],
    vitals: {
      spO2: 89,
      heartRate: 122,
      bloodPressure: "98/56",
      temperature: 39.2,
      recordedAt: now,
    },
    medications: [
      "Ceftriaxone 2g IV",
      "Levofloxacin 750mg IV",
      "Noradrenaline truyền liên tục",
      "Insulin Actrapid theo thang",
    ],
    labResults: [
      {
        name: "Bạch cầu",
        value: 19.6,
        unit: "K/uL",
        referenceRange: "4-10",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "Procalcitonin",
        value: 12.4,
        unit: "ng/mL",
        referenceRange: "<0.5",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "Lactate",
        value: 3.8,
        unit: "mmol/L",
        referenceRange: "<2",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "X-quang ngực",
        value: "Đông đặc thùy dưới phải",
        unit: "",
        referenceRange: "Bình thường",
        isAbnormal: true,
        recordedAt: now,
      },
      {
        name: "HbA1c",
        value: 8.9,
        unit: "%",
        referenceRange: "<6.5",
        isAbnormal: true,
        recordedAt: now,
      },
    ],
  },
];
